---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Say Hello
      condition: event.payload.message == "Testing webhook"
      action:
        run_job_template:
          name: hello
          organization: VSI

# curl -H 'Content-type: application/json' -d "{\"message\":\"Testing webhook\"}" 10.128.2.67:5000/endpoint
# curl -H "Content-type: application/json" -d '{"message":"Testing webhook"}' 10.128.2.67:5000/endpoint
