---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 192.168.23.0
        port: 5000
  rules:
    - name: Say Hello
      condition: event.payload.message == "Testing webhook"
      action:
        run_job_template:
          name: hello
          organization: VSI